name: SimpleCommands
main: me.shukbob.SimpleCommands.SimpleCommands

version: 1.0
commands:
      kill:
        description: Kill
      heal:
        description: Heal
      gm:
        description: Gamemode Toggle
      time:
        description: Set the world time
      server:
        description: Server Settings
      sc:
        description: SC Version